import path from 'path'
import { MeemAPI } from '../types/meem.generated'
import errors from './errors'

// eslint-disable-next-line
const packageJSON = require(path.join(process.cwd(), 'package.json'))

export default {
	version: packageJSON.version as string,
	errors,
	PORT: process.env.PORT ?? 1313,
	MEEM_DOMAIN:
		process.env.MEEM_DOMAIN ?? process.env.NETWORK === 'rinkeby'
			? 'https://dev.meem.wtf'
			: 'https://meem.wtf',
	SERVER_LISTENING: process.env.SERVER_LISTENING !== 'false',
	SERVER_ADMIN_KEY: process.env.SERVER_ADMIN_KEY ?? 'xGugNAB2PEX4uY4sPF',
	// JWT_SECRET:
	// 	process.env.JWT_SECRET ??
	// 	'ac741f40d71a2564e08180f5eb1cc9dd28e288ed75b33c34cba2fc18a3c31a64e719835877c7a6db9fdae8054037053172aba56f4dabc5f1b',
	JWT_RSA_PUBLIC_KEY: process.env.JWT_RSA_PUBLIC_KEY ?? '',
	JWT_RSA_PRIVATE_KEY: process.env.JWT_RSA_PRIVATE_KEY ?? '',
	JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN
		? +process.env.JWT_EXPIRES_IN
		: 604800, // 7 days
	SERVERLESS: process.env.SERVERLESS === 'true',
	LOG_LEVEL: process.env.LOG_LEVEL ?? 'warn',
	ENABLE_REQUEST_LOGGING: process.env.ENABLE_REQUEST_LOGGING === 'true',
	GENERATE_SHARED_TYPES: process.env.GENERATE_SHARED_TYPES === 'true',
	TESTING: process.env.TESTING === 'true',
	DISABLE_RATE_LIMIT: process.env.DISABLE_RATE_LIMIT === 'true',

	DATABASE_URL: process.env.DATABASE_URL ?? 'sqlite::memory:',
	// DATABASE_URL_TESTING:
	// 	process.env.DATABASE_URL_TESTING ||
	// 	`sqlite:${__dirname}/../../tmp/testing.db`,
	DISABLE_MIGRATIONS: process.env.DISABLE_MIGRATIONS === 'true',
	DISABLE_ORM_SYNC: process.env.DISABLE_ORM_SYNC === 'true',
	DATABASE_POOL_MAX: process.env.DATABASE_POOL_MAX
		? +process.env.DATABASE_POOL_MAX
		: 5,
	DATABASE_POOL_MIN: process.env.DATABASE_POOL_MIN
		? +process.env.DATABASE_POOL_MIN
		: 0,
	DATABASE_POOL_IDLE: process.env.DATABASE_POOL_IDLE
		? +process.env.DATABASE_POOL_IDLE
		: 10000,
	ORM_DISABLE: process.env.ORM_DISABLE === 'true',
	ORM_FORCE_SYNC: process.env.ORM_FORCE_SYNC === 'true',
	ORM_DISABLE_SSL: process.env.ORM_DISABLE_SSL === 'true',
	ORM_ALLOW_UNAUTHORIZED: process.env.ORM_ALLOW_UNAUTHORIZED === 'true',
	ORM_LOGGING: process.env.ORM_LOGGING === 'true',
	DOTENV_DEBUG: process.env.DOTENV_DEBUG === 'true',

	CORS_ALLOW_ALL: process.env.CORS_ALLOW_ALL === 'true',
	CORS_DEFAULT_ORIGIN: process.env.CORS_DEFAULT_ORIGIN ?? 'meem.wtf',
	CORS_ALLOWED_ORIGINS: process.env.CORS_ALLOWED_ORIGINS
		? process.env.CORS_ALLOWED_ORIGINS.split(',').map(o => o.trim())
		: ['clubs.link'],

	REDIS_URL: process.env.REDIS_URL,
	REDIS_ENABLED: process.env.REDIS_ENABLED !== 'false',
	// Default cache TTL in seconds
	REDIS_DEFAULT_TTL: process.env.REDIS_DEFAULT_TTL
		? +process.env.REDIS_DEFAULT_TTL
		: 300,
	// Only needed if redis is being shared by multiple API instances on different environments
	REDIS_KEY_PREFIX: process.env.REDIS_KEY_PREFIX,
	AWS_WEBSOCKET_GATEWAY_URL: process.env.AWS_WEBSOCKET_GATEWAY_URL,
	SERVERLESS_LOG_FULL_REQUEST: process.env.SERVERLESS_LOG_FULL_REQUEST,
	APP_AWS_ACCESS_KEY_ID: process.env.APP_AWS_ACCESS_KEY_ID ?? '',
	APP_AWS_SECRET_ACCESS_KEY: process.env.APP_AWS_SECRET_ACCESS_KEY ?? '',
	CHAIN_IDS: process.env.CHAIN_IDS
		? process.env.CHAIN_IDS.split(',').map(cid => +cid.trim())
		: [5],
	NETWORK: process.env.NETWORK
		? (process.env.NETWORK as MeemAPI.NetworkName)
		: ('' as MeemAPI.NetworkName),
	WALLET_PRIVATE_KEY: process.env.WALLET_PRIVATE_KEY ?? '',
	TWITTER_WALLET_PRIVATE_KEY: process.env.TWITTER_WALLET_PRIVATE_KEY ?? '',
	MEEM_PROXY_ADDRESS: process.env.MEEM_PROXY_ADDRESS ?? '',
	MEEM_ID_PROXY_ADDRESS: process.env.MEEM_ID_PROXY_ADDRESS ?? '',
	TWITTER_PROJECT_TOKEN_ID: process.env.TWITTER_PROJECT_TOKEN_ID ?? '',
	IPFS_CONTENT_GATEWAY_URL:
		process.env.IPFS_CONTENT_GATEWAY_URL ?? 'https://meem.mypinata.cloud',
	GITHUB_KEY: process.env.GITHUB_KEY ?? '',
	ETHERSCAN_API_KEY: process.env.ETHERSCAN_API_KEY ?? '',
	DYNAMODB_SOCKETS_TABLE: process.env.DYNAMODB_SOCKETS_TABLE ?? '',
	DYNAMODB_TWEET_CHECKPOINTS_TABLE:
		process.env.DYNAMODB_TWEET_CHECKPOINTS_TABLE ?? '',
	ENABLE_TEST_ENDPOINTS: process.env.ENABLE_TEST_ENDPOINTS === 'true',
	WEBSOCKETS_ENABLED: process.env.WEBSOCKETS_ENABLED === 'true',
	LAMBDA_MINT_FUNCTION: process.env.LAMBDA_MINT_FUNCTION ?? '',
	LAMBDA_REINITIALIZE_FUNCTION_NAME:
		process.env.LAMBDA_REINITIALIZE_FUNCTION_NAME ?? '',
	LAMBDA_CREATE_CLUB_SAFE_FUNCTION_NAME:
		process.env.LAMBDA_CREATE_CLUB_SAFE_FUNCTION_NAME ?? '',
	LAMBDA_MINT_ORIGINAL_FUNCTION:
		process.env.LAMBDA_MINT_ORIGINAL_FUNCTION ?? '',
	LAMBDA_CREATE_CONTRACT_FUNCTION:
		process.env.LAMBDA_CREATE_CONTRACT_FUNCTION ?? '',
	LAMBDA_MEEMID_UPDATE_FUNCTION:
		process.env.LAMBDA_MEEMID_UPDATE_FUNCTION ?? '',
	LAMBDA_AGREEMENT_BULK_MINT_FUNCTION:
		process.env.LAMBDA_AGREEMENT_BULK_MINT_FUNCTION ?? '',
	LAMBDA_AGREEMENT_ROLE_BULK_MINT_FUNCTION:
		process.env.LAMBDA_AGREEMENT_ROLE_BULK_MINT_FUNCTION ?? '',
	UPGRADE_CLUB_FUNCTION_NAME: process.env.UPGRADE_CLUB_FUNCTION_NAME ?? '',
	DISABLE_ASYNC_MINTING: process.env.DISABLE_ASYNC_MINTING === 'true',
	S3_BUCKET: process.env.S3_BUCKET ?? '',
	ENABLE_WHITELIST_TEST_DATA: process.env.ENABLE_WHITELIST_TEST_DATA === 'true',
	MAX_GAS_PRICE_GWEI: process.env.MAX_GAS_PRICE_GWEI
		? +process.env.MAX_GAS_PRICE_GWEI
		: 50,
	MIN_GASE_PRICE_GWEI: process.env.MIN_GASE_PRICE_GWEI
		? +process.env.MIN_GASE_PRICE_GWEI
		: 31,
	GAS_ESTIMATE_THRESHOLD_GWEI: process.env.GAS_ESTIMATE_THRESHOLD_GWEI
		? +process.env.GAS_ESTIMATE_THRESHOLD_GWEI
		: 10,
	ENABLE_TWITTER_LISTENERS: process.env.ENABLE_TWITTER_LISTENERS === 'true',
	TWITTER_CONSUMER_KEY: process.env.TWITTER_CONSUMER_KEY ?? '',
	TWITTER_CONSUMER_SECRET: process.env.TWITTER_CONSUMER_SECRET ?? '',
	TWITTER_AUTH_CALLBACK_URL: process.env.TWITTER_AUTH_CALLBACK_URL ?? '',
	TWITTER_BEARER_TOKEN: process.env.TWITTER_BEARER_TOKEN ?? '',
	TWITTER_MEEM_ACCOUNT_CONSUMER_KEY:
		process.env.TWITTER_MEEM_ACCOUNT_CONSUMER_KEY ?? '',
	TWITTER_MEEM_ACCOUNT_CONSUMER_SECRET:
		process.env.TWITTER_MEEM_ACCOUNT_CONSUMER_SECRET ?? '',
	TWITTER_MEEM_ACCOUNT_ID: process.env.TWITTER_MEEM_ACCOUNT_ID ?? '',
	TWITTER_MEEM_ACCOUNT_TOKEN: process.env.TWITTER_MEEM_ACCOUNT_TOKEN ?? '',
	TWITTER_MEEM_ACCOUNT_SECRET: process.env.TWITTER_MEEM_ACCOUNT_SECRET ?? '',
	MEEM_AUCTION_PROXY_ADDRESS: process.env.MEEM_AUCTION_PROXY_ADDRESS ?? '',
	MEEM_AUCTION_CURRENCY_ADDRESS:
		process.env.MEEM_AUCTION_CURRENCY_ADDRESS ?? '',
	ENABLE_CONTRACT_LISTENERS: process.env.ENABLE_CONTRACT_LISTENERS === 'true',
	ENABLE_PROVIDER_LISTENERS: process.env.ENABLE_PROVIDER_LISTENERS === 'true',
	MEEMPASS_DEFAULT_TWEETS_PER_DAY_QUOTA: process.env
		.MEEMPASS_DEFAULT_TWEETS_PER_DAY_QUOTA
		? +process.env.MEEMPASS_DEFAULT_TWEETS_PER_DAY_QUOTA
		: 0,
	ENABLE_VERBOSE_ERRORS: process.env.ENABLE_VERBOSE_ERRORS === 'true',
	MEEM_PROJECT_OWNER_ADDRESS: process.env.MEEM_PROJECT_OWNER_ADDRESS ?? '',
	DEFAULT_PAGINATION_LIMIT: process.env.DEFAULT_PAGINATION_LIMIT
		? +process.env.DEFAULT_PAGINATION_LIMIT
		: 20,
	ENABLE_PUPPETEER: process.env.ENABLE_PUPPETEER === 'true',
	ENABLE_URL_SCRAPER: process.env.ENABLE_URL_SCRAPER === 'true',
	MINT_GAS_LIMIT: process.env.MINT_GAS_LIMIT
		? process.env.MINT_GAS_LIMIT
		: '6000000',
	ENABLE_GUNDB: process.env.ENABLE_GUNDB === 'true',
	GUNDB_S3_BUCKET: process.env.GUNDB_S3_BUCKET ?? '',
	GUNDB_PASSWORD: process.env.GUNDB_PASSWORD ?? '',
	GUNDB_USER: process.env.GUNDB_USER ?? '',
	ENABLE_PROMPTS: process.env.ENABLE_PROMPTS === 'true',
	TWITTER_PROMPTS_PROJECT_TOKEN_ID:
		process.env.TWITTER_PROMPTS_PROJECT_TOKEN_ID ?? '',
	PINATA_API_KEY: process.env.PINATA_API_KEY ?? '',
	PINATA_API_SECRET: process.env.PINATA_API_SECRET ?? '',
	TWITTER_INTEGRATION_ID: process.env.TWITTER_INTEGRATION_ID ?? '',
	TWITTER_IDENTITY_INTEGRATION_ID:
		process.env.TWITTER_IDENTITY_INTEGRATION_ID ?? '',
	DISCORD_IDENTITY_INTEGRATION_ID:
		process.env.DISCORD_IDENTITY_INTEGRATION_ID ?? '',
	EMAIL_IDENTITY_INTEGRATION_ID:
		process.env.EMAIL_IDENTITY_INTEGRATION_ID ?? '',
	MEEM_BUNDLE_ID: process.env.MEEM_BUNDLE_ID ?? '',
	MEEM_PROXY_CONTRACT_ID: process.env.MEEM_PROXY_CONTRACT_ID ?? '',
	ADMIN_ROLE:
		'0xa49807205ce4d355092ef5a8a18f56e8913cf4a201fbe287825b095693c21775',
	MINTER_ROLE:
		'0x9f2df0fed2c77648de5860a4cc508cd0818c85b8b8a1ab4ceeef8d981c8956a6',
	UPGRADER_ROLE:
		'0x189ab7a9244df0848122154315af71fe140f3db0fe014031783b0946b8c9d2e3',
	GNOSIS_MASTER_CONTRACT_ADDRESS:
		process.env.GNOSIS_MASTER_CONTRACT_ADDRESS ?? '',
	GNOSIS_PROXY_CONTRACT_ADDRESS:
		process.env.GNOSIS_PROXY_CONTRACT_ADDRESS ?? '',
	GNOSIS_DEFAULT_CALLBACK_HANDLER:
		process.env.GNOSIS_DEFAULT_CALLBACK_HANDLER ?? '',
	DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID ?? '',
	DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET ?? '',
	DISCORD_AUTH_CALLBACK_URL: process.env.DISCORD_AUTH_CALLBACK_URL ?? '',
	AUTH0_APP_DOMAIN: process.env.AUTH0_APP_DOMAIN ?? '',
	AUTH0_CLIENT_ID: process.env.AUTH0_CLIENT_ID ?? '',
	AUTH0_CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET ?? '',
	AUTH0_VERIFY_EMAIL_CALLBACK_URL:
		process.env.AUTH0_VERIFY_EMAIL_CALLBACK_URL ?? '',
	PG_LOCK_RETRY_COUNT: process.env.PG_LOCK_RETRY_COUNT
		? +process.env.PG_LOCK_RETRY_COUNT
		: 3,
	PG_LOCK_TIMEOUT: process.env.PG_LOCK_TIMEOUT
		? +process.env.PG_LOCK_TIMEOUT
		: 10000,
	WALLET_LOCK_KEY: process.env.WALLET_LOCK_KEY ?? 'apiWallet',
	ARBITRUM_GAS_MULTIPLIER: process.env.ARBITRUM_GAS_MULTIPLIER
		? +process.env.ARBITRUM_GAS_MULTIPLIER
		: 6,
	JSON_RPC_MAINNET: process.env.JSON_RPC_MAINNET ?? '',
	JSON_RPC_CELO: process.env.JSON_RPC_CELO ?? 'https://rpc.ankr.com/celo',
	ALCHEMY_API_KEY_MAINNET: process.env.ALCHEMY_API_KEY_MAINNET ?? '',
	ALCHEMY_API_KEY_RINKEBY: process.env.ALCHEMY_API_KEY_RINKEBY ?? '',
	ALCHEMY_API_KEY_POLYGON: process.env.ALCHEMY_API_KEY_POLYGON ?? '',
	ALCHEMY_API_KEY_GOERLI: process.env.ALCHEMY_API_KEY_GOERLI ?? '',
	ALCHEMY_API_KEY_ARBITRUM_GOERLI:
		process.env.ALCHEMY_API_KEY_ARBITRUM_GOERLI ?? '',
	ALCHEMY_API_KEY_OPTIMISM_GOERLI:
		process.env.ALCHEMY_API_KEY_OPTIMISM_GOERLI ?? '',
	ALCHEMY_API_KEY_MUMBAI: process.env.ALCHEMY_API_KEY_MUMBAI ?? '',
	JSON_RPC_HARDHAT: process.env.JSON_RPC_HARDHAT ?? 'http://127.0.0.1:8545',
	PKP_CONTRACT_ADDRESS:
		process.env.PKP_CONTRACT_ADDRESS ??
		'0x86062B7a01B8b2e22619dBE0C15cbe3F7EBd0E92',
	PKP_MINT_COST: process.env.PKP_MINT_COST ?? '0.0001'
}
